#spring:
#application:
 #   name: api-gateway
#cloud:
 #   gateway:
  #    routes:
#- id: user_service
    #    uri: lb://user_service
   #     predicates:
    #    - Path=/user/**
        
    #  - id: contact_service
    #    uri: lb://contact_service
   #     predicates:
  #      - Path=/contact/**
 